# Generated by Django 2.1 on 2019-11-21 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('crawled_uri', models.URLField(max_length=400)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('url_id', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
